### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by al8n** [al8n/ruserf#3]
# Stage 1

- [ ] Add metrics
- [ ] Finish `status` method
- [ ] Refactor `handle_node_leave` method
- [ ] Adapt to newest version of `memberlist`.
- [ ] Testing
  - [ ] unit tests
  - [ ] Add CI
      - [ ] Code coverage over `75%`
- [ ] Documentation
  - [ ] `100%` document

# Stage 2
- [ ] Bindings
  - [ ] nodejs
  - [ ] python
  - [ ] wasmer
    - [ ] Basic support
    - [ ] Advanced support (allow users to implement `Delegate` trait by other languages and integrate it into `ruserf` by Wasmer).
- [ ] Tutorials
